language: cpp
compiler:
  - gcc
install:
  - export ANDROID="android-sdk-linux/tools/android"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#   - sudo apt-add-repository ppa:beineri/opt-qt52 -y
  - sudo apt-get update -qq
  - sudo apt-get remove g++ gcc g++-4.6 libstdc++6-4.6-dev
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
#   - sudo apt-get install -qq qt52declarative qt52graphicaleffects
#   - wget http://dev.rom1504.fr/android_armv7.tgz
#   - tar xzf android_armv7.tgz
#   - sudo cp -R android_armv7/ /opt/
#   - source /opt/qt52/bin/qt52-env.sh
#   - git clone git://gitorious.org/qt/qttools.git
#   - cd qttools/src/androiddeployqt/
#   - qmake
#   - make
#   - sudo make install
  - CI_HOME=`pwd`
  - sudo mkdir -p /opt
  - cd /opt
  - sudo wget http://dev.rom1504.fr/qt521_small.tgz -O - | sudo tar xz
  - cd $CI_HOME
  - wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86_64.tar.bz2 -O - | tar --absolute-names -jx
  - ls
  - wget http://dl.google.com/android/android-sdk_r22-linux.tgz -O - | tar zx
  - $ANDROID list sdk --extended -a
  - echo yes | $ANDROID update sdk -a --filter android-18 --no-ui --force

script:
  - /opt/Qt/5.2.1/gcc_64/bin/qmake --version
  - ./travis_script.sh

env:
  - secure: "i6PKhVKM8PP2CcR2C83FoeADp8MzzsNAd7hlE5oL0KFpf4lqOT0WQXErp0AZKRtOgzu19bCOzvH4j9nfwl5RGwX7++M1VYN8eAyqlxt9Kr0gju8QVWOzPyteWrEUV5LygqNSS7t8g13nPTAKeNedz7VWwvW7hoTkBMlTL5Jd5kw="

  

after_success:
  - if [ `git rev-parse --abbrev-ref HEAD` = master ] ; then exit 0 ; else exit 1 ; fi
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -pass "pass:$MY_SECRET_ENV" -in .travis/id_rsa_deploy.enc -out ~/.ssh/id_rsa -d -a
  - chmod 600 ~/.ssh/id_rsa
  - ./deploy.sh
  - sudo gcc usleep.c -o /bin/usleep
  - sudo apt-get install -qq xvfb xautomation x11-utils x11-apps
  - ./screenshot.sh
  - ./sendScreenShot.sh