language: cpp
compiler:
  - gcc
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get remove g++ gcc
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo apt-get install -qq qtdeclarative5-dev
script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make

env:
  - secure: "i6PKhVKM8PP2CcR2C83FoeADp8MzzsNAd7hlE5oL0KFpf4lqOT0WQXErp0AZKRtOgzu19bCOzvH4j9nfwl5RGwX7++M1VYN8eAyqlxt9Kr0gju8QVWOzPyteWrEUV5LygqNSS7t8g13nPTAKeNedz7VWwvW7hoTkBMlTL5Jd5kw="

  

after_success:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -pass "pass:$MY_SECRET_ENV" -in .travis/id_rsa_deploy.enc -out ~/.ssh/id_rsa -d -a
  - chmod 600 ~/.ssh/id_rsa

  - cd TvSeriesOrganizerApp
  - mv TvSeriesOrganizerApp TvSeriesOrganizer
  - tar czf TvSeriesOrganizer.tgz TvSeriesOrganizer
  
  - scp -o StrictHostKeyChecking=no TvSeriesOrganizer.tgz travis@download.rom1504.fr:download/TvSeriesOrganizer/
