language: cpp
compiler:
  - gcc
install:
  - build/installQt.sh
  - build/installAndroidTools.sh
  

script:
  - /opt/Qt/5.2.1/gcc_64/bin/qmake --version
  - build/travis_script.sh

env:
  - secure: "i6PKhVKM8PP2CcR2C83FoeADp8MzzsNAd7hlE5oL0KFpf4lqOT0WQXErp0AZKRtOgzu19bCOzvH4j9nfwl5RGwX7++M1VYN8eAyqlxt9Kr0gju8QVWOzPyteWrEUV5LygqNSS7t8g13nPTAKeNedz7VWwvW7hoTkBMlTL5Jd5kw="

after_success:
  - if [[ $MY_SECRET_ENV != "" ]] ; then build/travis_after_success.sh  ; fi
  
notifications:
  irc: "chat.freenode.net#TvSeriesOrganizer"
