language: cpp
compiler:
  - gcc
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-add-repository ppa:beineri/opt-qt521 -y
  - sudo apt-get update -qq
  - sudo apt-get remove g++ gcc g++-4.6 libstdc++6-4.6-dev
  - sudo apt-get install -qq g++-4.8 gcc-4.8
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo apt-get install -qq qt52declarative qt52graphicaleffects
  - source /opt/qt52/bin/qt52-env.sh

script:
  - qmake --version
  - qmake
  - make

env:
  - secure: "i6PKhVKM8PP2CcR2C83FoeADp8MzzsNAd7hlE5oL0KFpf4lqOT0WQXErp0AZKRtOgzu19bCOzvH4j9nfwl5RGwX7++M1VYN8eAyqlxt9Kr0gju8QVWOzPyteWrEUV5LygqNSS7t8g13nPTAKeNedz7VWwvW7hoTkBMlTL5Jd5kw="

  

after_success:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -pass "pass:$MY_SECRET_ENV" -in .travis/id_rsa_deploy.enc -out ~/.ssh/id_rsa -d -a
  - chmod 600 ~/.ssh/id_rsa
  - ./deploy.sh
  - sudo gcc usleep.c -o /bin/usleep
  - sudo apt-get install -qq xvfb xautomation x11-utils x11-apps
  - ./screenshot.sh
  - ./sendScreenShot.sh